version: '3.1'

services:
  # Nginx will receive all sites and switch for each one
  # Additional configurations can be done in ./nginx/conf.d
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/html:/usr/share/nginx/html
    # extra_hosts:
    #   - "somehost:162.242.195.82"
    #   - "otherhost:50.31.209.229"

  # Kanban service
  kanban:
    image: kanboard/kanboard:v1.2.0
    volumes:
      # Copy config.php.sample to config.php and edit.
      - ./kanboard/config.php:/var/www/app/data/config.php
      - kanban_data:/var/www/app/data
      - kanban_plugins:/var/www/app/plugins

  worker:
    image: kanboard/kanboard:v1.2.0
    volumes:
      - ./kanboard/config.php:/var/www/app/data/config.php
      - kanban_data:/var/www/app/data
      - kanban_plugins:/var/www/app/plugins
    entrypoint: bash -c '/var/www/app/cli worker'

  beanstalk:
    image: schickling/beanstalkd

  # Roundcube service
  roundcube:
    image: filhocf/roundcube
    environment:
      ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE: 25M
    volumes:
      # Copy config.php.sample to config.php and edit.
      - ./roundcube/config:/var/roundcube/config

  # Web2canvas service
  web2canvas:
    image: filhocf/web2canvas
    volumes:
      # Copy example_appconfig.json to appconfig.json and edit.
      - ./web2canvas/appconfig.json:/usr/local/web2py/applications/web2canvas/private/appconfig.json

  # Etherpad service
  etherpad:
    image: unihalle/etherpad-lite
    volumes:
      - ./etherpad/settings.json:/opt/etherpad-lite/settings.json
    environment:
      ETHERPAD_TITLE: Pad do DEIN
      ETHERPAD_PORT: 80
      ETHERPAD_ADMIN_USER: etherpad
      ETHERPAD_ADMIN_PASSWORD: etherpad
      ETHERPAD_DB_TYPE: mysql
      ETHERPAD_DB_HOST: mydb
      ETHERPAD_DB_PORT: 3306
      ETHERPAD_DB_USER: etherpad
      ETHERPAD_DB_NAME: etherpad
      ETHERPAD_DB_PASS: etherpad

  # Wordpress service
  wordpress:
    image: wordpress:fpm-alpine
    environment:
      WORDPRESS_DB_HOST: mydb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  # IdeiaX service
  ideax:
    image: filhocf/ideax
    volumes:
      # Copy config.php.sample to config.php and edit.
      - ./ideax/env:/var/www/ideax/.env

  # Nextcloud service
  web:
    image: nginx
    volumes:
      - ./nextcloud/nginx/:/etc/nginx/conf.d
      - ./nextcloud/redis/redis.config.php:/var/www/html/config/redis.config.php
      - nextcloud:/var/www/html

  nextcloud:
    image: nextcloud:fpm
    volumes:
      - nextcloud:/var/www/html

  redis:
    image: redis

  # RocketChat service
  chat:
    image: rocketchat/rocket.chat:0.62.2
    command: /scripts/entrypoint.sh
    deploy:
        replicas: 1
        update_config:
            parallelism: 1
            delay: 15s
    environment:
        ROOT_URL: https://c.example.com/
        ADMIN_EMAIL: admin@example.com
        ADMIN_PASS: 123456
        MONGO_URL: mongodb://mongodb:27017/rocketchat
        MONGO_OPLOG_URL: mongodb://mongodb:27017/local
        INSTANCE_IP: $$(hostname -i | cut -f2 -d\  )
    volumes:
        - rocketchat_avatars:/app/uploads
        - rocketchat_uploads:/var/uploads
        - rocketchat_incremental:/backups
        - ./scripts:/scripts
    ports:
        - 3000


  # Databases PostgreSQL and Mysql
  pgdb:
    image: postgres:10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresl_password
    volumes:
      - pg_data:/var/lib/postgresql/data

  mydb:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: mysql_password
    volumes:
      - my_data:/var/lib/mysql

  mongodb:
    image: mongo:3.4
    command: --smallfiles --oplogSize 128 --replSet rs0
    volumes:
      - mongo_data:/data/db
    deploy:
      placement:
        constraints: [node.role == manager]


volumes:
  pg_data:
  my_data:
  mongo_data:
  kanban_data:
  kanban_plugins:
  nextcloud:
  rocketchat_avatars:
  rocketchat_uploads:
  rocketchat_incremental:
  wp-content:
